/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Conexion.Conexion;
import Controlador.Ctrl_Registro;
import Modelo.Registro;
import java.awt.HeadlessException;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan Esteban
 */
public class InterModificarRegistro extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterAgregarSalida
     */
    
    private int idRegistro;
    public InterModificarRegistro() {
        initComponents();
        this.obtenerTablaRegistros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRegistro = new javax.swing.JTable();
        btnModificarRegistro = new javax.swing.JButton();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        txtHoraSalida = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdRegistro = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("SALIDA ; CRAI");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204,80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Modificar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jTableRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRegistro);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 430, 160));

        btnModificarRegistro.setBackground(new java.awt.Color(0, 102, 51));
        btnModificarRegistro.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnModificarRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarRegistro.setText("Modificar");
        btnModificarRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 100, -1, 40));

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado", "I", "S" }));
        jPanel1.add(jComboBoxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 170, -1));

        txtHoraSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraSalidaActionPerformed(evt);
            }
        });
        jPanel1.add(txtHoraSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 100, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hora Salida");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, 20));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Id Registro");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, 20));
        jPanel1.add(txtIdRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 100, -1));

        jPanel2.setBackground(new java.awt.Color(187, 187, 187));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 432, 163));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 540, 400));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoMenuPersona.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHoraSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraSalidaActionPerformed

    private void btnModificarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarRegistroActionPerformed
        // TODO add your handling code here:
        ActualizarRegistro();
    }//GEN-LAST:event_btnModificarRegistroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificarRegistro;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRegistro;
    private javax.swing.JTextField txtHoraSalida;
    private javax.swing.JTextField txtIdRegistro;
    // End of variables declaration//GEN-END:variables


  private void ActualizarRegistro() {
        Registro registro = new Registro();
        Ctrl_Registro controlRegistro = new Ctrl_Registro();
        String txtEstado = jComboBoxEstado.getSelectedItem().toString().trim();

        // Verificar si los campos obligatorios están completos
        if (txtHoraSalida.getText().equals("")) {
            // Mostrar un mensaje si algún campo está vacío
            JOptionPane.showMessageDialog(null, "Complete todos los campos");

        } else {
            if (txtEstado.equalsIgnoreCase("Estado")) {
                JOptionPane.showMessageDialog(null,"Ingrese el estado del registro"); 
                
            } else {

                try {
                    // Configurar los datos del registro con los valores de los campos de texto
                   
                    registro.setHoraSalida(txtHoraSalida.getText().trim());
                    registro.setEstado(txtEstado);

                    if (controlRegistro.actualizar(registro,idRegistro)) {
                        JOptionPane.showMessageDialog(null, "Registro Actualizado");
                        
                        this.obtenerTablaRegistros();
                        this.jComboBoxEstado.setSelectedItem("Estado");
                        this.Limpiar();
                        
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al Guardar, verifique si la persona esta en la Base de Datos");
                    }

                }// Manejar posibles errores al convertir el ID de persona a entero
                catch (HeadlessException | NumberFormatException e) {
                    System.out.println("Error en: " + e);
                }

            }

        }

    }
     private void obtenerTablaRegistros() {
        Connection con = (Connection) Conexion.conectar();
        DefaultTableModel model = new DefaultTableModel();
        String sql = "select * from tb_registro";
        Statement st;

        try {
            st = (Statement) con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            this.jTableRegistro = new JTable(model);
            this.jScrollPane1.setViewportView(this.jTableRegistro);

            model.addColumn("idRegistro");
            model.addColumn("idPersona");
            model.addColumn("Hora Entrada");
            model.addColumn("Hora Salida");
            model.addColumn("Fecha");
            model.addColumn("Estado");
         

            while (rs.next()) {
                Object fila[] = new Object[6];

                for (int i = 0; i < 6; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                model.addRow(fila);

            }
            con.close();

        } catch (SQLException e) {
            System.out.println("Error al llenar la tabla Registro: " + e);
        }jTableRegistro.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jTableRegistro.rowAtPoint(e.getPoint());
                int columna_point = 0;

                if (fila_point > -1) {
                    idRegistro = (int) model.getValueAt(fila_point, columna_point);
                    EnviarDatosRegistroSeleccionado(idRegistro);
                }
            }
        });

   }
  
  private void Limpiar(){
      txtHoraSalida.setText("");
      txtIdRegistro.setText("");
  }
  
   private void EnviarDatosRegistroSeleccionado(int idRegistro) {

        try {
            Connection con = (Connection) Conexion.conectar();
            PreparedStatement pst = (PreparedStatement) con.prepareStatement(
                    "select * from tb_registro where idRegistro ='" + idRegistro + "'");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                txtIdRegistro.setText(rs.getString("IdRegistro"));
 
            }
            con.close();
        } catch (SQLException e) {
            System.out.println("Error al seleccionar el registro: " + e);
        }
    }

}
