/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import java.sql.Connection;
import Conexion.Conexion;
import Controlador.Ctrl_Reserva;
import Modelo.Reserva;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import Conexion.Conexion;
import Modelo.Persona;
import java.sql.ResultSet;
import java.sql.SQLException;



/**
 *
 * @author Juan Esteban
 */
public class InterHacerReserva extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterHacerReserva
     */
    
    
      int obtenerIdPersona = 0;
    public InterHacerReserva() {
        initComponents();
        this.CargarId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jComboBoxIdHorario = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtHoraSalida = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxIdPersona = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("RESERVA ; CRAI");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204,80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Reserva");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        txtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFechaKeyPressed(evt);
            }
        });
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 170, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hora");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 40, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jornada");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, 20));

        txtHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraActionPerformed(evt);
            }
        });
        txtHora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHoraKeyPressed(evt);
            }
        });
        jPanel1.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 170, 30));

        btnGuardar.setBackground(new java.awt.Color(0, 102, 51));
        btnGuardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 170, -1));

        jComboBoxIdHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una jornada", "1. Mañana [8:00 AM - 11:00 AM].", "2. Tarde [1:00 PM - 6:00 PM].", "3. Noche [7:00 PM - 9:00 PM]." }));
        jPanel1.add(jComboBoxIdHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 170, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Id de la Persona");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        txtHoraSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraSalidaActionPerformed(evt);
            }
        });
        txtHoraSalida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHoraSalidaKeyPressed(evt);
            }
        });
        jPanel1.add(txtHoraSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 170, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hora Salida");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 80, 30));

        jComboBoxIdPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un ID" }));
        jPanel1.add(jComboBoxIdPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 170, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 360, 350));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ee405b9f-c88f-4e24-893c-798271fbc402.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 398, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtFechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
        GuardarReserva();
        }
    }//GEN-LAST:event_txtFechaKeyPressed

    private void txtHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraActionPerformed

    private void txtHoraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoraKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtHoraSalida.requestFocus();
        }
    }//GEN-LAST:event_txtHoraKeyPressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
        GuardarReserva();

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtHoraSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraSalidaActionPerformed

    private void txtHoraSalidaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoraSalidaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtFecha.requestFocus();
        }
    }//GEN-LAST:event_txtHoraSalidaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> jComboBoxIdHorario;
    private javax.swing.JComboBox<String> jComboBoxIdPersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtHoraSalida;
    // End of variables declaration//GEN-END:variables

    private void Limpiar() {
        txtHora.setText("");
        txtHoraSalida.setText("");
        txtFecha.setText("");

    }

    private void GuardarReserva() {
        Reserva reserva = new Reserva();
        Ctrl_Reserva controlReserva = new Ctrl_Reserva();
        String txtIdHorario = jComboBoxIdHorario.getSelectedItem().toString().trim();
        String txtIdPersona = jComboBoxIdPersona.getSelectedItem().toString().trim();

        if (txtHora.getText().equals("") || txtFecha.getText().equals("") || txtHoraSalida.getText().isEmpty()) {
            // Mostrar un mensaje si algún campo está vacío
            JOptionPane.showMessageDialog(null, "Complete todos los campos");

        } else {
            if (txtIdHorario.equalsIgnoreCase("Seleccione una jornada")) {
                JOptionPane.showMessageDialog(null, "Ingrese una jornada");

            } else {
                if (txtIdPersona.equalsIgnoreCase("Seleccione un ID")) {
                    JOptionPane.showMessageDialog(null, "Seleccione una persona");
                } else {

                    try {

                        reserva.setIdPersona(Integer.parseInt(txtIdPersona));
                        reserva.setHoraEntrada(txtHora.getText().trim());
                        reserva.setHoraSalida(txtHoraSalida.getText().trim());
                        switch (txtIdHorario) {
                            case "1. Mañana [8:00 AM - 11:00 AM].":
                                txtIdHorario = "1";
                                break;
                            case "2. Tarde [1:00 PM - 6:00 PM].":
                                txtIdHorario = "2";
                                break;
                            case "3. Noche [7:00 PM - 9:00 PM].":
                                txtIdHorario = "3";
                                break;
                        }
                        reserva.setIdHorario(Integer.parseInt(txtIdHorario));
                        reserva.setFecha(txtFecha.getText().trim());

                        if (controlReserva.guardar(reserva)) {
                            JOptionPane.showMessageDialog(null, "Registro guardado");
                            this.jComboBoxIdHorario.setSelectedItem("Seleccione una jornada");
                            this.jComboBoxIdPersona.setSelectedItem("Seleccione un ID");
                            this.Limpiar();
                        }

                    } catch (HeadlessException | NumberFormatException e) {
                        System.out.println("Error en: " + e);
                    }
                }

            }
        }

    }
    
     private void CargarId() {
        Connection cn = (Connection) Conexion.conectar();
        String sql = "select * from tb_persona";
        Statement st;
        try {
            st = (Statement) cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBoxIdPersona.removeAllItems();
            jComboBoxIdPersona.addItem("Seleccione un ID");
            while (rs.next()) {
                jComboBoxIdPersona.addItem(rs.getString("idPersona"));
            }
            cn.close();

        } catch (SQLException e) {
            System.out.println("Error al cargar el id de las personas");
        }
    }
     
       private int IdCategoria() {
        String sql = "select * from tb_persona where idPersona = '" + this.jComboBoxIdPersona.getSelectedItem() + "'";
        Statement st;

        try {
            Connection cn = (Connection) Conexion.conectar();
            st = (Statement) cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                obtenerIdPersona = rs.getInt("idPersona");
            }
        } catch (SQLException e) {
            System.out.println("Error al obtener el idPersona");
        }
        return obtenerIdPersona;
    }
    
}
